### ISSUE TITLE
AABB centre computation in all implementations is wrong

### ISSUE THREAD

**Issue by spullara** [athas/raytracers#10]
I was porting to Java and noticed that in each of the various language examples they seem to have a similar definition:

```
let centre (aabb: aabb) = {
  x = aabb.min.x +. aabb.max.x -. aabb.min.x;
  y = aabb.min.y +. aabb.max.y -. aabb.min.y;
  z = aabb.min.z +. aabb.max.z -. aabb.min.z;
}
```

But that is identical to:

```
let centre (aabb: aabb) = {
  x = aabb.max.x;
  y = aabb.max.y;
  z = aabb.max.z;
}
```

Am I missing something?

**Comment by athas** [comment]
Yeah, that's a bug, but it doesn't really matter for the BVH construction for these scenes, and it's consistently buggy in all the implementations, so I have not bothered fixing it yet.
