### ISSUE TITLE
Rust

### ISSUE THREAD

**Issue by tbillington** [athas/raytracers#17]
Not sure how much you're allowing to tweak compiler settings on a per implementation basis, but rust does have a few more tricks you can enable based on https://doc.rust-lang.org/cargo/reference/profiles.html & https://doc.rust-lang.org/rustc/codegen-options/index.html 🙂

In Cargo.toml

```toml
[profile.release]
opt-level = 3
lto = true
panic = 'abort'
codegen-units = 1
```

And setting this env variable before compiling to let rustc know it can take advantage of newer cpu instructions available to your specific cpu architecture

```
RUSTFLAGS="-C target-cpu=native"
```

**Comment by athas** [comment]
This seems to have near-zero impact on performance on my machine.  If my timing was less crude, I'd probably be able to say that it's within statistical uncertainty.  I'm inclined to not do this, mostly to avoid confusion about whether it is the reason Rust does so well.

**Comment by tbillington** [comment]
Makes sense! How much those options help varies greatly between each project due to a number of factors. Thanks for giving them a shot!
