### ISSUE TITLE
Request benchmark with PolyML

### ISSUE THREAD

**Issue by hai-nguyen-van** [athas/raytracers#18]
Hello, I am wondering how if PolyML would be scalable enough to belong to this benchmark test :)

**Comment by athas** [comment]
I would certainly like to see that!

**Comment by athas** [comment]
Here's a sequential implementation for a start: https://github.com/athas/raytracers/blob/master/sml/ray.sml

It's pretty slow.  I'll see if I can figure out PolyMLs parallelism primitives.

**Comment by hai-nguyen-van** [comment]
Do you compile with `polyc` or interpret with `poly` only ?

**Comment by athas** [comment]
[`polyc`](https://github.com/athas/raytracers/blob/master/sml/Makefile#L4)

**Comment by athas** [comment]
From what I can see, Poly/MLs facilities for parallelism are more or less equivalent to pthreads.  They may be fast, but I'm not particularly interested in writing low-level multithreaded code, as that goes against what I'm trying to investigate here.  If someone can find a deterministic parallel programming library for PolyML, then we can use that, but I will not write it myself.

**Comment by hai-nguyen-van** [comment]
I see 😊 Thanks for investigating!
