### ISSUE TITLE
Use of image processing lib

### ISSUE THREAD

**Issue by NinoFloris** [athas/raytracers#28]
As Haskell is now using a specialized lib for image processing, could other langs join in? 

https://hackage.haskell.org/package/massiv-io

**Comment by athas** [comment]
It's not really used for image processing, just go get decent parallel arrays.  It's a band-aid on the fact that Haskell doesn't supply decent parallelism out of the box.  From what I can see, we only use a tiny fraction of what `massiv` provides.

I hope other languages don't need specialised image processing libraries (nor is this task really about image processing at all).  I'd rather not this just become a comparison between who put the most effort into a library.

**Comment by NinoFloris** [comment]
If I'm not mistaken `writeImage` is directly exported from massive-io and `toPixel8` is also from a lib that's depended on via massive-io. So I would be inclined to disagree a bit there.

Would be fairly similar usage in F# but in our case it would also be free SIMD :)

**Comment by athas** [comment]
But those are not used in the part of the program that is timed.

**Comment by NinoFloris** [comment]
Though render is part of the program that's timed right?

https://github.com/lehins/raytracers/blob/099e7b1c4e134c89fd6950d40dcc053c2a7381ad/haskell/Raytracing.hs#L181-L187
toPixel8 is used there

In any case I'm ok not doing it, just wanted to know where you draw the line :)

**Comment by minad** [comment]
What about implementing a separate F# simd version? It might make sense to have different implementations for comparison.

**Comment by athas** [comment]
None of the implementations use any kind of explicit SIMD.  It's fine if the compilers can make automatic use of SIMD instructions, but I'd rather keep the programs somewhat high-level and "idiomatic", although I realise that's a nebulous term and a blurry line.

That use of toPixel8 is going to be an infinitesimally small part of the run-time, since it's just converting three floats to integers and adding them together.  There's not really much clever implementation that can be hidden in the library.

**Comment by minad** [comment]
@athas I agree completely regarding Haskell. Massiv is used only to work around the incapable monad-par. And all the implementations are almost a literal translation, which is very good for comparison.

It might still be interesting to see how such a simd version/fully optimized would look like in contrast. I've seen other benchmarks which keep two versions around - one naive/idiomatic and one fully optimized. Maybe that would work here too? In the case of Haskell, the fully optimized version with everything unboxed wouldn't look nice, I am sure. The question is if there are libraries which still keep the high-level functional look and feel but optimize better. Maybe using a F# simd library or a Haskell version which uses massiv to its full extent.

**Comment by NinoFloris** [comment]
>That use of toPixel8 is going to be an infinitesimally small part of the run-time

I know was just pointing out uses that were in fact timed, like I said It's fine, I don't want to be pedantic.

A SIMD version would be interesting, I agree with @minad's opinion there but I'll close it for now :)
